import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BusFront,Star,History,ArrowLeft,ArrowDownUp,RefreshCw,MapPin,ChevronRight,Radio,Clock,Navigation,WifiOff,ChevronDown} from 'lucide-react';
import './style.css';
import {useBus} from './useBus';
import {RouteLibrary,useSavedRoutes,FavoriteButton} from './RouteLibrary';
import {RegionPicker} from './RegionPicker';
const text=v=>v==null||v===''?'—':typeof v==='object'?JSON.stringify(v):String(v);
const time=d=>new Date(d).toLocaleTimeString('zh-CN',{hour12:false});

function Raw({label,value}){return <details className="raw"><summary>{label}<ChevronDown size={15}/></summary><pre>{JSON.stringify(value,null,2)}</pre></details>}
function App(){
 const saved=useSavedRoutes();
 const [libraryView,setLibraryView]=useState('all'),[query,setQuery]=useState('');
 const bus=useBus(),[tab,setTab]=useState('stations'),[selectedCar,setSelectedCar]=useState(null),[now,setNow]=useState(Date.now());
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);
 const {route,routes,data,stations}=bus;const cars=Array.isArray(data?.carPoses)?data.carPoses:[];
 const stale=bus.received&&now-bus.received>30000;
 const select=r=>{saved.visit(r);bus.choose(r);setSelectedCar(null);setTab('stations');window.scrollTo({top:0});};
 const openLibrary=view=>{bus.back();setLibraryView(view);setQuery('');window.scrollTo({top:0});};
 const switchDetail=next=>{setTab(next);requestAnimationFrame(()=>document.querySelector('.content-panel')?.scrollIntoView({block:'start'}));};
 const opposite=route&&routes.find(r=>r.rid===route.rid&&r.upDown!==route.upDown);
 return <div className="app">
 <aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();bus.back();}}><span className="brand-icon"><BusFront size={23}/></span><span>沿途<small>BUSTRACK</small></span></a><div className="side-section">出行</div><button className="nav active" onClick={bus.back}><Navigation size={18}/>实时公交<ChevronRight size={15}/></button><div className="side-note">● 大连 · 昌赫客运<p>每一程，心中有数。</p></div></aside>
 <main><header><RegionPicker/><button className={'connection connection-button '+bus.connection} onClick={bus.retry} disabled={bus.connection==='connecting'} aria-label={bus.connection==='connecting'?'正在连接':bus.connection==='connected'?'已连接，点击重新连接':'已断开，点击重新连接'} title="点击重新连接"><i/>{bus.connection==='connected'?'已连接':bus.connection==='connecting'?'连接中':'已断开 · 重连'}{bus.connection!=='connected'&&<RefreshCw size={13} className={bus.connection==='connecting'?'spin':''}/>}</button></header>
 {bus.error&&<div className="notice"><WifiOff size={17}/>{bus.error}</div>}
 {!route?<><RouteLibrary routes={routes} saved={saved} select={select} connection={bus.connection} view={libraryView} setView={setLibraryView} query={query} setQuery={setQuery}/></>:<>

 <section className={"route-hero "+(bus.received&&cars.length===0?"no-vehicles-hero":"")}><div className="hero-top"><div><div className="eyebrow">昌赫客运 / 实时线路</div><h1>{route.rname}</h1></div><FavoriteButton route={route} saved={saved} expanded/></div><div className="hero-direction"><span>{route.fstname}</span><span className="direction-line">→</span><span>{route.lstname}</span><button disabled={!opposite} onClick={()=>select(opposite)} aria-label="切换方向"><ArrowDownUp size={19}/></button></div><div className="hero-meta"><span><Clock size={14}/>{route.fdtime||'—'} — {route.ldtime||'—'}</span><span>线路 ID {route.rid}</span><span>方向 {route.upDown??0}</span></div></section>
 {bus.received&&cars.length===0&&<div className="no-vehicles-notice" role="status"><BusFront size={22}/><div><strong>当前未返回运营车辆</strong><p>该方向本次车辆列表为空，可能尚未发车、已收班或数据暂缺。站点信息仍可查看。</p></div></div>}<div className="metrics"><div><span>本次返回车辆</span><strong>{bus.received?cars.length:'—'}<small>辆</small></strong></div><div><span>下一班发车字段</span><strong>{data?.ndTime||'—'}</strong></div><div><span>线路站点</span><strong>{stations.length||'—'}<small>站</small></strong></div></div>
 <div className="refresh-row"><span className={stale?'stale':''}><Radio size={14}/>{bus.received?`${time(bus.received)} 接收${stale?' · 数据可能已过期':''}`:'等待车辆数据'}</span><div><label><input type="checkbox" checked={bus.automatic} onChange={e=>bus.setAutomatic(e.target.checked)}/>自动刷新</label><button disabled={bus.loading||bus.connection!=='connected'} onClick={bus.refresh} aria-label="刷新车辆"><RefreshCw size={17} className={bus.loading?'spin':''}/></button></div></div>
 <div className="detail-grid"><section className="content-panel"><div className="tabs"><button className={tab==='stations'?'selected':''} onClick={()=>setTab('stations')}>站点实况 <span>{stations.length}</span></button><button className={tab==='vehicles'?'selected':''} onClick={()=>setTab('vehicles')}>车辆详情 <span>{cars.length}</span></button></div>
 {tab==='stations'?<div className="timeline">{stations.length?stations.map((s,i)=>{const here=cars.filter(c=>Number(c.staNO)===Number(s.staNO));return <div className={'station '+(here.length?'occupied':'')} key={`${s.staNO}:${i}`}><div className="track"><span>{i+1}</span></div><div className="station-content"><div className="station-name">{s.staName}{i===0&&<em>始</em>}{i===stations.length-1&&<em>终</em>}</div>{here.map(c=><button className="bus-chip" key={c.carID} onClick={()=>{setSelectedCar(c.carID);setTab('vehicles');}}><BusFront size={15}/><span>{c.inOut===0?'到站':'站点附近'} · {c.carID}</span>{c.distance>0&&<small>{c.distance} m*</small>}<ChevronRight size={13}/></button>)}</div></div>;}):<div className="empty"><MapPin size={28}/><h3>{bus.loading?'正在获取站点':'暂无站点数据'}</h3><p>车辆坐标可在「车辆详情」查看。</p></div>}</div>:<div className="vehicle-list">{cars.map(c=><article className={'vehicle '+(selectedCar===c.carID?'highlight':'')} key={c.carID}><div className="vehicle-heading"><BusFront size={20}/><strong>{c.carID}</strong><span>站序 {c.staNO}</span></div><p className="vehicle-station">{stations.find(s=>Number(s.staNO)===Number(c.staNO))?.staName||'站名未提供'}</p><dl>{[['纬度','lat'],['经度','lng'],['距离原值','distance'],['进出站标记','inOut'],['客流字段 PasFlow','PasFlow'],['拥挤字段 CongLeve','CongLeve'],['StaSpace','StaSpace'],['ArvInfo','ArvInfo']].map(([label,k])=><div key={k}><dt>{label}</dt><dd>{text(c[k])}</dd></div>)}</dl><Raw label="完整车辆信息" value={c}/></article>)}{!cars.length&&<div className="empty"><BusFront size={28}/><h3>{bus.loading?'正在查询车辆':!bus.received?'尚未获取车辆数据':'本次返回 0 辆车'}</h3><p>请稍后刷新，未返回车辆不代表线路停运。</p></div>}</div>}
 </section><aside className="info-panel"><h3>这一程的信息</h3><dl><div><dt>运营方</dt><dd>大连昌赫客运</dd></div><div><dt>刷新间隔</dt><dd>{bus.automatic?'10 秒 · 前台刷新':'手动刷新'}</dd></div><div><dt>位置形式</dt><dd>站序 + 经纬度</dd></div></dl><p className="info-note">位置由数据服务返回。坐标系尚未验证，暂以站点实况与原始坐标展示。接收时间不代表车辆定位时间。</p><p className="info-note">* 距离按原网页以米展示，参考站点及进出站标记的确切定义待核实。客流字段的 0 不代表空车。</p><Raw label="完整线路信息" value={route}/><Raw label="完整站点数据" value={bus.stationData}/><Raw label="完整位置回包" value={data}/></aside></div></>}
 </main><nav className="bottom-nav" aria-label={route?'线路操作':'主导航'}>{route?<><button onClick={()=>openLibrary('all')}><ArrowLeft size={21}/><span>全部线路</span></button><button className={tab==='stations'?'active':''} aria-pressed={tab==='stations'} onClick={()=>switchDetail('stations')}><MapPin size={21}/><span>站点</span></button><button className={tab==='vehicles'?'active':''} aria-pressed={tab==='vehicles'} onClick={()=>switchDetail('vehicles')}><BusFront size={21}/><span>车辆</span></button><button disabled={bus.loading||bus.connection!=='connected'} onClick={bus.refresh}><RefreshCw size={21} className={bus.loading?'spin':''}/><span>{bus.loading?'刷新中':'刷新'}</span></button></>:<>{[['all','线路',BusFront],['favorites','收藏',Star],['recent','最近',History]].map(([id,label,Icon])=><button key={id} className={libraryView===id?'active':''} aria-current={libraryView===id?'page':undefined} onClick={()=>openLibrary(id)}><Icon size={21}/><span>{label}</span></button>)}</>}</nav>{saved.message&&<div className="save-toast" role="status">{saved.message}</div>}<div className="mobile-brand"><BusFront size={16}/>沿途 <span>BUSTRACK</span></div></div>;
}
createRoot(document.getElementById('root')).render(<App/>);



